language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;
    sudo apt-get -y purge libgraphviz-dev; 
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
  fi

install:
- sudo pip install numpy cython

script: 
- sudo python setup.py install
- nosetests -s -v