language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;
    sudo apt-get -y purge libgraphviz-dev; 
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
  fi

install:

- sudo pip install numpy cython scipy nose # to help pip from testpypi

- sudo -E pip install -i https://testpypi.python.org/pypi pfnet

- git clone -b dev https://github.com/ttinoco/OPTALG.git
- cd OPTALG
- sudo pip install -r requirements.txt
- sudo python setup.py install
- cd ../

script: 
- sudo python setup.py install
- nosetests -s -v